### ISSUE TITLE
Add a high-level description of the API first on /syntax.html

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/sphinxcontrib-prettyproof#35]
I found it a little bit confusing that the first example starts with `{proof:proof}`. I think if there were a short section like "all directives in this package follow the pattern `{proof:<title>}` or something like this, I may have been a bit less-confused. Just sharing in case it's helpful!

**Comment by najuzilu** [comment]
How's this:

> This package utilizes a [Sphinx domain](https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html) - named "proof" - to describe and link typeset markup objects (theorems, proofs, corollaries, etc.) which we think belong together. All directives follow the pattern `{<domain_name>:<typeset>}` while all the roles follow the pattern `{<domain_name>:ref}`. To utilize any directive in the `proof` domain follow the pattern `{proof:<typeset>}`. To reference any directive follow the pattern `{proof:ref}`.

**Comment by najuzilu** [comment]
Closing since this has been addressed here #39.
