### ISSUE TITLE
Documentation similarities to / different decisions from sphinxcontrib-proof

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/sphinxcontrib-prettyproof#37]
We should make it clear how this package differs from [`sphinxcontrib-proof`](https://github.com/sphinx-contrib/proof) since they will both look very similar to one another. What are the major design decisions that are different? Why was a new package created? When would you use one vs. the other?

**Comment by najuzilu** [comment]
In the workings. We've already discussed this in issue #8 :-)

**Comment by choldgraf** [comment]
Oops! It's a dupe! Gonna close in favor of #8 :-)
